version: "3.8"

services:
  mysql:
    image: mysql:9.1.0
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata_project:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT_LOCAL}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 15

  identity-service:
    build:
      context: ./backend/identity-service
    depends_on:
      - mysql
    env_file: ./.env
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${IDENTITY_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  coupon-service:
    build:
      context: ./backend/coupon-service
    depends_on:
      - mysql
    env_file: ./.env
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: ${COUPON_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  gateway:
    build:
      context: ./backend/gateway
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - coupon-service

  frontend:
    build:
      context: ./frontend/app
    ports:
      - "3000:5173"
    depends_on:
      - gateway

volumes:
  dbdata_project:
